"""Initial schema

Revision ID: a02aba970024
Revises: 
Create Date: 2026-08-01 08:48:22.684556

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a02aba970024'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False, comment='Normalised (lowercase) email address — used for login.'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Display name (free-form, preserves original capitalisation).'),
    sa.Column('avatar_url', sa.Text(), nullable=True, comment='Profile picture URL (set by OAuth provider or user upload).'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment="Argon2/bcrypt digest of the user's password.  NULL for OAuth-only accounts."),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False = soft-deleted / suspended account.'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='True once the email address has been confirmed.'),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False, comment='Grants admin-level access across all resources.'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent successful login.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_is_active_created_at', 'users', ['is_active', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('owner_id', sa.UUID(), nullable=True, comment='User who created this project.  NULL if the owner was deleted.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Human-readable project title.'),
    sa.Column('genre', sa.String(length=100), nullable=True, comment="Film genre (e.g. 'Thriller', 'Documentary')."),
    sa.Column('logline', sa.Text(), nullable=True, comment='One-sentence story summary.'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='Lifecycle stage: draft | in_progress | completed | archived.'),
    sa.Column('script_draft', sa.Text(), nullable=True, comment='Full AI-generated script text, stored for re-use without re-running the agent.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','in_progress','completed','archived')", name='ck_projects_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.create_index('ix_projects_status_created_at', 'projects', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Owning project.'),
    sa.Column('agent_type', sa.String(length=100), nullable=False, comment="Identifier for the agent pipeline that was run, e.g. 'full_pipeline', 'location_scout', 'script_writer'."),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False, comment='Lifecycle stage: pending | running | completed | failed.'),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full AgentState dict captured at the last graph checkpoint.'),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ordered list of LangChain BaseMessage dicts.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment="Human-readable error if status='failed'."),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the session reached a terminal state.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name='ck_agent_sessions_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_sessions_project_id_created_at', 'agent_sessions', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_agent_sessions_project_id_status', 'agent_sessions', ['project_id', 'status'], unique=False)
    op.create_table('budgets',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Owning project (unique — one budget per project).'),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False, comment="ISO 4217 currency code (e.g. 'USD', 'EUR', 'GBP')."),
    sa.Column('total_estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True, comment='Denormalised sum of all BudgetItem amounts.  Updated by the application layer whenever items change.'),
    sa.Column('contingency_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Contingency reserve as a percentage of total (e.g. 15.00 = 15%).'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='Budget stage: draft | approved | revised | locked.'),
    sa.Column('assumptions', sa.Text(), nullable=True, comment='Agent-generated assumptions behind the cost estimates.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','approved','revised','locked')", name='ck_budgets_status'),
    sa.CheckConstraint('contingency_pct IS NULL OR (contingency_pct >= 0 AND contingency_pct <= 100)', name='ck_budgets_contingency_pct'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('ix_budgets_project_id', 'budgets', ['project_id'], unique=False)
    op.create_table('locations',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Owning project.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable location name (e.g. 'Griffith Observatory')."),
    sa.Column('address', sa.Text(), nullable=True, comment='Full formatted address string from Google Places.'),
    sa.Column('place_id', sa.String(length=255), nullable=True, comment='Google Places stable place identifier.'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='WGS-84 latitude  (-90 to +90).'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='WGS-84 longitude (-180 to +180).'),
    sa.Column('description', sa.Text(), nullable=True, comment='Freeform notes about the location (access, permits, etc.).'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='Approval stage: draft | scouted | approved | rejected.'),
    sa.Column('ai_suitability_score', sa.Float(), nullable=True, comment='Gemini-assigned suitability score (0–10).'),
    sa.Column('ai_notes', sa.Text(), nullable=True, comment='Gemini-generated narrative about why this location fits the project.'),
    sa.Column('weather_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Cached OpenWeather forecast JSON for this coordinate.'),
    sa.Column('places_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw Google Places API result object for this location.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','scouted','approved','rejected')", name='ck_locations_status'),
    sa.CheckConstraint('ai_suitability_score IS NULL OR (ai_suitability_score >= 0 AND ai_suitability_score <= 10)', name='ck_locations_suitability_score_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'place_id', name='uq_locations_project_place')
    )
    op.create_index('ix_locations_project_id', 'locations', ['project_id'], unique=False)
    op.create_index('ix_locations_status', 'locations', ['status'], unique=False)
    op.create_table('risk_reports',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Owning project.'),
    sa.Column('overall_risk_level', sa.String(length=20), nullable=True, comment='Aggregate risk rating: low | medium | high | critical.'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Agent-generated executive summary of all identified risks.'),
    sa.Column('recommendations', sa.Text(), nullable=True, comment='Top-level mitigation recommendations from the agent.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("overall_risk_level IN ('low','medium','high','critical')", name='ck_risk_reports_overall_risk_level'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_reports_overall_risk_level', 'risk_reports', ['overall_risk_level'], unique=False)
    op.create_index('ix_risk_reports_project_id', 'risk_reports', ['project_id'], unique=False)
    op.create_table('schedules',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Owning project (unique — one schedule per project).'),
    sa.Column('total_shoot_days', sa.Integer(), nullable=True, comment='Total number of scheduled filming days.'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='Schedule stage: draft | approved | in_progress | completed.'),
    sa.Column('notes', sa.Text(), nullable=True, comment='General production insights and scheduling rationale from the agent.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','approved','in_progress','completed')", name='ck_schedules_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('ix_schedules_project_id', 'schedules', ['project_id'], unique=False)
    op.create_table('budget_items',
    sa.Column('budget_id', sa.UUID(), nullable=False, comment='Parent budget.'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Cost category / department: above_the_line | below_the_line | production | post_production | equipment | locations | cast | crew | other.'),
    sa.Column('label', sa.String(length=255), nullable=False, comment="Human-readable label for this line item (e.g. 'Director Fee')."),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment="Estimated cost in the budget's currency (non-negative)."),
    sa.Column('notes', sa.Text(), nullable=True, comment='Agent rationale or production notes for this estimate.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('above_the_line','below_the_line','production','post_production','equipment','locations','cast','crew','other')", name='ck_budget_items_category'),
    sa.CheckConstraint('amount >= 0', name='ck_budget_items_amount_non_negative'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budget_items_budget_id', 'budget_items', ['budget_id'], unique=False)
    op.create_index('ix_budget_items_category', 'budget_items', ['category'], unique=False)
    op.create_table('risk_items',
    sa.Column('report_id', sa.UUID(), nullable=False, comment='Parent risk report.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment="Short, descriptive risk title (e.g. 'Rain forecast on exterior shoot day')."),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Production area affected: weather | budget | schedule | legal_permits | cast_crew | equipment | location | health_safety | other.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the risk and its potential impact.'),
    sa.Column('probability', sa.Integer(), nullable=False, comment='Likelihood of the risk occurring: 1 (rare) → 5 (near-certain).'),
    sa.Column('impact', sa.Integer(), nullable=False, comment='Severity if the risk materialises: 1 (negligible) → 5 (critical).'),
    sa.Column('mitigation', sa.Text(), nullable=True, comment='Recommended action to reduce or eliminate the risk.'),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False, comment='Resolution stage: open | acknowledged | mitigated | closed.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('weather','budget','schedule','legal_permits','cast_crew','equipment','location','health_safety','other')", name='ck_risk_items_category'),
    sa.CheckConstraint("status IN ('open','acknowledged','mitigated','closed')", name='ck_risk_items_status'),
    sa.CheckConstraint('impact BETWEEN 1 AND 5', name='ck_risk_items_impact_range'),
    sa.CheckConstraint('probability BETWEEN 1 AND 5', name='ck_risk_items_probability_range'),
    sa.ForeignKeyConstraint(['report_id'], ['risk_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_items_category', 'risk_items', ['category'], unique=False)
    op.create_index('ix_risk_items_report_id', 'risk_items', ['report_id'], unique=False)
    op.create_index('ix_risk_items_status', 'risk_items', ['status'], unique=False)
    op.create_table('scenes',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Owning project.'),
    sa.Column('location_id', sa.UUID(), nullable=True, comment='The approved filming location chosen for this scene (nullable).'),
    sa.Column('scene_number', sa.Integer(), nullable=False, comment='1-based sequential scene number within the project.'),
    sa.Column('title', sa.String(length=255), nullable=True, comment="Short scene heading (e.g. 'INT. DETECTIVE OFFICE – DAY')."),
    sa.Column('description', sa.Text(), nullable=True, comment='Scene action lines / brief.'),
    sa.Column('location_query', sa.String(length=512), nullable=True, comment='Search string sent to Google Maps / Places.'),
    sa.Column('int_ext', sa.String(length=10), nullable=True, comment='Interior/exterior flag: INT | EXT | INT/EXT.'),
    sa.Column('time_of_day', sa.String(length=10), nullable=True, comment='Lighting condition: DAY | NIGHT | DUSK | DAWN.'),
    sa.Column('location_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Google Places API response for the scouted location.'),
    sa.Column('weather_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='OpenWeather current + forecast data for the location.'),
    sa.Column('ai_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Gemini-generated shooting suggestions for this scene.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("int_ext IN ('INT', 'EXT', 'INT/EXT') OR int_ext IS NULL", name='ck_scenes_int_ext'),
    sa.CheckConstraint("time_of_day IN ('DAY', 'NIGHT', 'DUSK', 'DAWN') OR time_of_day IS NULL", name='ck_scenes_time_of_day'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'scene_number', name='uq_scenes_project_scene_number')
    )
    op.create_index('ix_scenes_location_id', 'scenes', ['location_id'], unique=False)
    op.create_index('ix_scenes_project_id', 'scenes', ['project_id'], unique=False)
    op.create_table('schedule_days',
    sa.Column('schedule_id', sa.UUID(), nullable=False, comment='Parent schedule.'),
    sa.Column('location_id', sa.UUID(), nullable=True, comment='Primary filming location for the day (NULL if multi-location).'),
    sa.Column('shoot_date', sa.Date(), nullable=False, comment='Calendar date for this shoot day (YYYY-MM-DD).'),
    sa.Column('day_number', sa.Integer(), nullable=False, comment='Sequential day number within the schedule (1-based).'),
    sa.Column('scene_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ordered JSONB array of Scene UUID strings to be filmed on this day.  Order within the array is the planned shooting order.'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Day-specific production notes (crew call time, weather contingency, etc.).'),
    sa.Column('call_time', sa.String(length=10), nullable=True, comment='Crew call time in HH:MM (24-hour) format.'),
    sa.Column('estimated_wrap_time', sa.String(length=10), nullable=True, comment='Estimated wrap time in HH:MM (24-hour) format.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'shoot_date', name='uq_schedule_days_schedule_date')
    )
    op.create_index('ix_schedule_days_schedule_id', 'schedule_days', ['schedule_id'], unique=False)
    op.create_index('ix_schedule_days_shoot_date', 'schedule_days', ['shoot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_days_shoot_date', table_name='schedule_days')
    op.drop_index('ix_schedule_days_schedule_id', table_name='schedule_days')
    op.drop_table('schedule_days')
    op.drop_index('ix_scenes_project_id', table_name='scenes')
    op.drop_index('ix_scenes_location_id', table_name='scenes')
    op.drop_table('scenes')
    op.drop_index('ix_risk_items_status', table_name='risk_items')
    op.drop_index('ix_risk_items_report_id', table_name='risk_items')
    op.drop_index('ix_risk_items_category', table_name='risk_items')
    op.drop_table('risk_items')
    op.drop_index('ix_budget_items_category', table_name='budget_items')
    op.drop_index('ix_budget_items_budget_id', table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index('ix_schedules_project_id', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_risk_reports_project_id', table_name='risk_reports')
    op.drop_index('ix_risk_reports_overall_risk_level', table_name='risk_reports')
    op.drop_table('risk_reports')
    op.drop_index('ix_locations_status', table_name='locations')
    op.drop_index('ix_locations_project_id', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_budgets_project_id', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_agent_sessions_project_id_status', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_project_id_created_at', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index('ix_projects_status_created_at', table_name='projects')
    op.drop_index('ix_projects_owner_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_users_is_active_created_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
