from pydantic import BaseModel, Field 
#pydantic is a data validation library, it acts as a gatekeeper for my code.
#Ensuring any data entered into the system matches the exact structure
#Basemodel is the core building block of Pydanitc,
#=========================================================================
from typing import List, Optional 
#This imports Python type hints
#It tells Python what kind of data a variable should contain.
#Optional means one value may exist, or it may be None.
#=========================================================================
from google.adk.agents import Agent, LlmAgent
#ADK stands for Agent Development Kit, it is a framework of building AI agents


class Scene(BaseModel):
# BaseModel is a class that comes from Pydantic,
# --- Auto validation
# --- JSON Exporting, BaseModel takes my entire class object and transforms all data into a JSON format.
    scene_number: str = Field(description="Sequential scene number as it appears in the script")

    location_setting: str = Field(description="Short Description of the location, e.g. 'urban alley'")

    indoor_or_not: str = Field(description="'Indoor', 'Outdoor', or 'Unspecified'")

    time_of_day: str = Field(default=None, description="Time of day for the scene")

    weather_of_scene: str = Field(default=None, description="Weather conditions for the scene")

    characters_in_scene: List[str] = Field(description="List of characters present in the scene")

    props_in_scene: List[str] = Field(description="List all props that are present in the scene")

    shooting_requirements: Optional[List[str]] = Field(default=None, description="List of shooting requirements for the scene, e.g. 'weapon on set', 'stunt', 'night shoot', 'VFX', 'crowd scene', 'animal', 'minor on set'")

#Notice: The extraction_Instruction prompt is generated by AI:
EXTRACTION_INSTRUCTION = """
You are the Director Agent for a film pre-production assistant.

Analyze the provided screenplay and break it down scene by scene.

Rules:
1. Create one Scene entry per distinct scene heading (INT./EXT.), in order.
2. List every named character who appears or speaks in that scene.
3. Props must be scene-specific (e.g. "revolver"), not generic categories.
4. Flag any non-standard shooting requirements per scene (stunts, weapons,
   night shoots, crowd scenes, animals, minors on set, VFX).
5. Only infer a value (time_of_day, weather, etc.) when there is clear,
   explicit textual evidence in that scene. Do not invent production details.
   Example: "Heavy rain falls outside" -> weather = "rain".
   Example: "John enters, rain-soaked" -> this describes John's state, NOT
   confirmed current weather -> leave weather as null unless corroborated
   elsewhere in the same scene.
6. If something cannot be inferred with reasonable confidence, use null
   rather than guessing.
Return ONLY the structured JSON matching the required schema. Do not include
any commentary outside the JSON.
Screenplay:
{script_text}
"""


#=======================================================================================
director_agent = LlmAgent(
    #LlmAgent is a class provided by Google ADK
    #It warps an LLM call into a reusable "agent" object.
    name="director_agent", # An identifer for this agent
    model="gemini-2.5-pro",
    instruction= Extraction_Instruction,
    output_schema=Scene,
    output_key= "extracted_data"#It tells the ADK framework where to save the LLM's final validated response
    )